name: ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.7.0

      - name: Install NPM dependencies
        run: yarn install

      - name: Build Gatsby website
        run: yarn build

  release_docker_image:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request'}}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: iamskok/gatsby-seo
          labels: |
            org.opencontainers.image.authors=Vladimir Skok <skok@vova.io>
            org.opencontainers.image.documentation=https://github.com/iamskok/gatsby-seo/blob/master/README.md
            org.opencontainers.image.source=https://github.com/iamskok/gatsby-seo
            org.opencontainers.image.url=https://hub.docker.com/repository/docker/iamskok/gatsby-seo
            org.opencontainers.image.title=gatsby-seo
            org.opencontainers.image.description=GraphiQL environment for gatsby-seo.netlify.app
            org.opencontainers.image.version=${{ steps.semantic.outputs.new_release_version }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            iamskok/gatsby-seo:latest
            iamskok/gatsby-seo:${{ steps.semantic.outputs.new_release_version }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: release_docker_image
    steps:
      - uses: actions/checkout@v2

      - name: Create `.env` file
        uses: SpicyPizza/create-envfile@v1.1
        with:
          envkey_DOMAIN: ${{ secrets.DOMAIN }}
          envkey_EMAIL: ${{ secrets.EMAIL }}
          envkey_SITE_URL: ${{ secrets.SITE_URL }}
          directory: ${{ github.workspace }}
          file_name: .env

      - name: Copy files to remote host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
          source: .env,docker-compose.yml
          target: /root

      - name: Start Docker containers on remote host
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
          script: |
            docker-compose --file /root/docker-compose.yml \
              --env-file /root/.env pull
            docker-compose --file /root/docker-compose.yml \
              --env-file /root/.env up --detach
            docker image prune --force
